#!/usr/bin/env python3
"""
Helper script to insert Q1-filtered analysis cell into the notebook
"""
import json
import sys

notebook_path = r"c:\Users\dunnmk\wilsontew-data-analysis\FourC_OneShot_Python_Report.ipynb"

# Read the notebook
with open(notebook_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Find cell 17 (the AS-stratified analysis cell with ID 97e0c40c)
target_cell_id = '97e0c40c'
target_index = None

for i, cell in enumerate(nb['cells']):
    if cell.get('id') == target_cell_id:
        target_index = i
        break

if target_index is None:
    print(f"Could not find cell with ID {target_cell_id}")
    sys.exit(1)

# Create the new cell
new_cell = {
    "cell_type": "code",
    "execution_count": None,
    "id": "filtered-analysis-q1",
    "metadata": {},
    "outputs": [],
    "source": [
        "# ==============================================================================\n",
        "# FILTERED ANALYSIS: Excluding Q1 (Lowest AS scores - Self-Ligation Artifacts)\n",
        "# ==============================================================================\n",
        "print('\\n' + '='*80)\n",
        "print('FILTERED 4C ANALYSIS: Excluding Q1 (Lowest Alignment Scores)')\n",
        "print('='*80 + '\\n')\n",
        "\n",
        "# Step 1: Identify Q1 threshold\n",
        "as_clean_q1 = readlen_df_with_quality.dropna(subset=['AS']).copy()\n",
        "as_clean_q1['qscore_quantile'] = pd.qcut(as_clean_q1['AS'], q=5, labels=False, duplicates='drop')\n",
        "\n",
        "# Get Q1 (lowest quintile) max value\n",
        "q1_max = as_clean_q1[as_clean_q1['qscore_quantile'] == 0]['AS'].max()\n",
        "q1_min = as_clean_q1[as_clean_q1['qscore_quantile'] == 0]['AS'].min()\n",
        "print(f'Q1 AS range: {q1_min:.0f} - {q1_max:.0f}')\n",
        "print(f'Filtering out reads with AS <= {q1_max:.0f}\\n')\n",
        "\n",
        "# Step 2: Filter out Q1 from best_alignments\n",
        "best_alignments_filtered = best_alignments[best_alignments['AS'] > q1_max].copy()\n",
        "n_removed = len(best_alignments) - len(best_alignments_filtered)\n",
        "pct_removed = 100.0 * n_removed / len(best_alignments)\n",
        "\n",
        "print(f'Original alignment count: {len(best_alignments):,}')\n",
        "print(f'After Q1 removal: {len(best_alignments_filtered):,}')\n",
        "print(f'Reads removed: {n_removed:,} ({pct_removed:.1f}%)\\n')\n",
        "\n",
        "# Step 3: ChrV analysis before and after filtering\n",
        "chrv_before = len(best_alignments[best_alignments['chrom'] == 'chrV'])\n",
        "chrv_after = len(best_alignments_filtered[best_alignments_filtered['chrom'] == 'chrV'])\n",
        "chrv_removed = chrv_before - chrv_after\n",
        "chrv_pct_before = 100.0 * chrv_before / len(best_alignments)\n",
        "chrv_pct_after = 100.0 * chrv_after / len(best_alignments_filtered)\n",
        "\n",
        "print(f'ChrV analysis:')\n",
        "print(f'  Before filtering: {chrv_before:,} reads ({chrv_pct_before:.2f}%)')\n",
        "print(f'  After filtering: {chrv_after:,} reads ({chrv_pct_after:.2f}%)')\n",
        "print(f'  ChrV reads removed: {chrv_removed:,} ({100.0*chrv_removed/chrv_before:.1f}% of chrV reads)')\n",
        "print(f'  Improvement: {chrv_pct_before - chrv_pct_after:.2f} percentage points reduction in chrV dominance\\n')\n",
        "\n",
        "# Step 4: Rebuild binned contacts for filtered data\n",
        "df_filt = best_alignments_filtered.copy()\n",
        "df_filt = df_filt[df_filt['chrom'].notna() & (df_filt['chrom'] != '*')].copy()\n",
        "df_filt['bin_start'] = ((df_filt['pos'] - 1) // BIN_SIZE) * BIN_SIZE + 1\n",
        "df_filt['bin_end'] = df_filt['bin_start'] + BIN_SIZE - 1\n",
        "df_filt['bin_id'] = df_filt['chrom'].astype(str) + ':' + df_filt['bin_start'].astype(str) + '-' + df_filt['bin_end'].astype(str)\n",
        "\n",
        "bin_counts_filtered = (\n",
        "    df_filt.groupby(['sample', 'time_point', 'chrom', 'bin_start', 'bin_end', 'bin_id'], as_index=False)\n",
        "      .size()\n",
        "      .rename(columns={'size': 'count'})\n",
        ")\n",
        "bin_counts_filtered['freq'] = bin_counts_filtered.groupby('sample')['count'].transform(lambda x: x / x.sum())\n",
        "\n",
        "print(f'Binned contacts (filtered): {len(bin_counts_filtered):,} bins')\n",
        "\n",
        "# Step 5: Generate TOP CONTACT BINS plot (filtered)\n",
        "print('\\nGenerating top contact bins plot (Q1-filtered)...\\n')\n",
        "\n",
        "def _short_bin_label_filt(bin_id: str):\n",
        "    if ':' not in str(bin_id):\n",
        "        return str(bin_id)\n",
        "    chrom, span = str(bin_id).split(':', 1)\n",
        "    if '-' not in span:\n",
        "        return str(bin_id)\n",
        "    start_s, end_s = span.split('-', 1)\n",
        "    try:\n",
        "        start_k = int(start_s) // 1000\n",
        "        end_k = int(end_s) // 1000\n",
        "        return f\\\"{chrom}:{start_k}k-{end_k}k\\\"\n",
        "    except ValueError:\n",
        "        return str(bin_id)\n",
        "\n",
        "chrom_order_index = {c: i for i, c in enumerate(CHROM_ORDER)}\n",
        "fallback_colors = sns.color_palette('husl', 24).as_hex()\n",
        "\n",
        "for sample_name, sdf in bin_counts_filtered.groupby('sample'):\n",
        "    chrom_rank = (\n",
        "        sdf.groupby('chrom', as_index=False)['count'].sum()\n",
        "        .sort_values('count', ascending=False)\n",
        "        .head(CONTACT_PLOT_TOP_CHROMS)\n",
        "    )\n",
        "    chosen_chroms = set(chrom_rank['chrom'].tolist())\n",
        "\n",
        "    candidate = sdf[sdf['chrom'].isin(chosen_chroms)].copy()\n",
        "    candidate = candidate.sort_values(['chrom', 'count'], ascending=[True, False])\n",
        "    per_chrom_top = candidate.groupby('chrom', as_index=False).head(CONTACT_PLOT_BINS_PER_CHROM).copy()\n",
        "\n",
        "    p = per_chrom_top.sort_values('count', ascending=False).head(CONTACT_PLOT_MAX_BARS).copy()\n",
        "    p['bin_label_short'] = p['bin_id'].map(_short_bin_label_filt)\n",
        "\n",
        "    p['chrom_order'] = p['chrom'].map(lambda x: chrom_order_index.get(x, 10_000))\n",
        "    p = p.sort_values(['chrom_order', 'count'], ascending=[True, False]).reset_index(drop=True)\n",
        "\n",
        "    hue_order = [c for c in CHROM_ORDER if c in set(p['chrom'])]\n",
        "    extra_chroms = sorted([c for c in pd.unique(p['chrom']) if c not in set(hue_order)])\n",
        "    hue_order.extend(extra_chroms)\n",
        "\n",
        "    palette_map = {}\n",
        "    for i, chrom in enumerate(hue_order):\n",
        "        palette_map[chrom] = CHROM_PALETTE.get(chrom, fallback_colors[i % len(fallback_colors)])\n",
        "\n",
        "    x_order = p['bin_label_short'].tolist()\n",
        "\n",
        "    plt.figure(figsize=(15, 5))\n",
        "    ax = sns.barplot(\n",
        "        data=p,\n",
        "        x='bin_label_short',\n",
        "        y='count',\n",
        "        hue='chrom',\n",
        "        order=x_order,\n",
        "        hue_order=hue_order,\n",
        "        dodge=False,\n",
        "        palette=palette_map\n",
        "    )\n",
        "    ax.set_title(f'Top contact bins (Q1-filtered, balanced by chromosome) | {sample_name}')\n",
        "    ax.set_xlabel('Genomic bin (short label)')\n",
        "    ax.set_ylabel('Read count (best-hit)')\n",
        "\n",
        "    n_labels = len(p)\n",
        "    step = max(1, n_labels // 16)\n",
        "    for i, tick in enumerate(ax.get_xticklabels()):\n",
        "        tick.set_rotation(70)\n",
        "        tick.set_fontsize(8)\n",
        "        tick.set_visible(i % step == 0)\n",
        "\n",
        "    top_n_annot = min(8, len(p))\n",
        "    top_rows = p.sort_values('count', ascending=False).head(top_n_annot)\n",
        "    x_lookup = {lab: idx for idx, lab in enumerate(x_order)}\n",
        "    for _, row in top_rows.iterrows():\n",
        "        x_idx = x_lookup.get(row['bin_label_short'])\n",
        "        if x_idx is not None:\n",
        "            ax.text(\n",
        "                x_idx,\n",
        "                row['count'],\n",
        "                f\\\"{int(row['count']):,}\\\",\n",
        "                ha='center',\n",
        "                va='bottom',\n",
        "                fontsize=8,\n",
        "                rotation=90\n",
        "            )\n",
        "\n",
        "    plt.legend(title='chrom', bbox_to_anchor=(1.02, 1), loc='upper left')\n",
        "    plt.tight_layout()\n",
        "    plt.show()\n",
        "\n",
        "# Step 6: Generate ALL BINS plot (Q1-filtered)\n",
        "print('Generating all contact bins plot (Q1-filtered)...\\n')\n",
        "\n",
        "for sample_name, sdf in bin_counts_filtered.groupby('sample'):\n",
        "    p_all = sdf.copy()\n",
        "    p_all['chrom_order'] = p_all['chrom'].map(lambda x: chrom_order_index.get(x, 10_000))\n",
        "    p_all = p_all.sort_values(['chrom_order', 'chrom', 'bin_start'], ascending=[True, True, True]).reset_index(drop=True)\n",
        "    p_all['bin_label_short'] = p_all['bin_id'].map(_short_bin_label_filt)\n",
        "\n",
        "    hue_order_all = [c for c in CHROM_ORDER if c in set(p_all['chrom'])]\n",
        "    extra_chroms_all = sorted([c for c in pd.unique(p_all['chrom']) if c not in set(hue_order_all)])\n",
        "    hue_order_all.extend(extra_chroms_all)\n",
        "\n",
        "    palette_map_all = {}\n",
        "    for i, chrom in enumerate(hue_order_all):\n",
        "        palette_map_all[chrom] = CHROM_PALETTE.get(chrom, fallback_colors[i % len(fallback_colors)])\n",
        "\n",
        "    x_order_all = p_all['bin_label_short'].tolist()\n",
        "\n",
        "    fig_w = max(18, min(46, 0.16 * len(p_all)))\n",
        "    plt.figure(figsize=(fig_w, 6))\n",
        "    ax_all = sns.barplot(\n",
        "        data=p_all,\n",
        "        x='bin_label_short',\n",
        "        y='count',\n",
        "        hue='chrom',\n",
        "        order=x_order_all,\n",
        "        hue_order=hue_order_all,\n",
        "        dodge=False,\n",
        "        palette=palette_map_all\n",
        "    )\n",
        "    ax_all.set_title(f'All contact bins (Q1-filtered, color-coded by chromosome) | {sample_name}')\n",
        "    ax_all.set_xlabel('Genomic bin (short label)')\n",
        "    ax_all.set_ylabel('Read count (best-hit)')\n",
        "\n",
        "    n_labels_all = len(p_all)\n",
        "    step_all = max(1, n_labels_all // 35)\n",
        "    for i, tick in enumerate(ax_all.get_xticklabels()):\n",
        "        tick.set_rotation(80)\n",
        "        tick.set_fontsize(7)\n",
        "        tick.set_visible(i % step_all == 0)\n",
        "\n",
        "    plt.legend(title='chrom', bbox_to_anchor=(1.02, 1), loc='upper left')\n",
        "    plt.tight_layout()\n",
        "    plt.show()\n",
        "\n",
        "print('✓ Filtered contact bin analysis complete!')\n"
    ]
}

# Insert the new cell after the target cell
nb['cells'].insert(target_index + 1, new_cell)

# Write the notebook back
with open(notebook_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)

print(f"Successfully inserted Q1-filtered analysis cell after cell {target_index}")
print(f"Total cells now: {len(nb['cells'])}")
